### ISSUE TITLE
Obstruct Power Doesn't

### ISSUE THREAD

**Issue by Cheeseness** [Double-Fine-Game-Club/pongball#104]
The obstruct power should prevent a player's paddle from moving.

Rather than blocking via physics (which gets awkward if the paddle is moving at speed), it's probably best to just set velocity to 0 and disable player movement.

**Comment by ghost** [comment]
Is that the intended use, or is it supposed to block the ball?

**Comment by Cheeseness** [comment]
It's meant to be an offensive power that freezes a player's paddle. @osse101, you designed them - could you confirm in case I've got my wires crossed?

**Comment by ghost** [comment]
Either way is fine with me, just wondering.

**Comment by osse101** [comment]
The design is to restrict the movement of the opponents paddle.  My aim is to stop them from defending half of their area.  And that has turned into 'throwing' the cube at their paddle and if it hits then they are frozen.  
The obstruct object is solid so it repels balls.

There are still a couple directions it could go.

(its much more broken in net play)

**Comment by Cheeseness** [comment]
Closed by #133
