### ISSUE TITLE
Fix 'rubberband' controls seen on non-host side

### ISSUE THREAD

**Issue by VideogameScrapbook** [Double-Fine-Game-Club/pongball#123]
@lightsoda and I confirmed the following on both of our ends (my average ping to his computer is pretty high: 183ms): The host player moves fine on both ends. However, the host cannot see the non-host move (except gradually 'drift' upwards. The non-host can move on his end, but the movement rubber bands towards the center. Then the rubber banding origin drifts upwards towards the top of the screen. We were both using the Windows "Pongball 2017-04-26_c10ab24b build.

**Comment by Cheeseness** [comment]
@osse101 said it didn't happen after rebuilding the client. Could be a busted build. Can you confirm?

**Comment by VideogameScrapbook** [comment]
@Cheeseness , I can help re-test if you post an exe somewhere that two of us could try (to ensure we're using exact same exe rather than building potentially subtly different exes).

**Comment by Cheeseness** [comment]
I'm on Linux and you're on Windows, so there's always the potential for subtle diffrences!

**Comment by fragmental** [comment]
How did you check the ping?

**Comment by Cheeseness** [comment]
Resolved by #169
