### ISSUE TITLE
Update LogoSwitcher with latest assets

### ISSUE THREAD

**Issue by fragmental** [Double-Fine-Game-Club/pongball#128]
There are a few.  There are some directions https://github.com/Double-Fine-Game-Club/pongball/blob/master/Assets/entities/ui/Logo_Instructions.txt 

Stretch goal, add code that automatically changes the logo every x seconds

**Comment by Cheeseness** [comment]
What's missing? So far as I'm aware it's only Mythalore's and that's only because it came in this morning.

**Comment by Cheeseness** [comment]
This is done so far as I'm aware. @Mythalore's came in with #134
