### ISSUE TITLE
Adjust Gamepad Sensitivity

### ISSUE THREAD

**Issue by Cheeseness** [Double-Fine-Game-Club/pongball#145]
Movement sensitivity on gamepads feels a bit high (could also be higher on some gamepads than others).

**Comment by fragmental** [comment]
http://www.third-helix.com/2013/04/12/doing-thumbstick-dead-zones-right.html this could possibly prove useful.

**Comment by Cheeseness** [comment]
Closing this with changes in #157. Further tuning can be done, but I'm happy with this for now.
