### ISSUE TITLE
Bug:  Music Next button is buggy

### ISSUE THREAD

**Issue by fragmental** [Double-Fine-Game-Club/pongball#151]
This is my fault.  My code.  So I feel it's my responsibility.  I'm not entirely sure the best way to fix it, though.  I thought some more experienced programmers @lightsoda @Cheeseness @jctwood or others, whose skill level I'm not currently aware of, might have some ideas.

Here's the code https://github.com/Double-Fine-Game-Club/pongball/blob/8b8fb3f49588987e6c0cea78c22ee04e02d5fd3f/Assets/scripts/audio/MusicPlayer.cs

The relevant code is public void PlayNextSong() it stops the coroutine that plays the song, changes the song index and then starts the coroutine again.  For some reason this makes the songs end too soon.  I suspect it's related to the "yield waitforseconds" but I'm unsure.

Super easy fix is to just ~~enable~~ disable the next song button, if this doesn't get fixed before Humble Bundle.

**Comment by fragmental** [comment]
I happened to have a more experienced coder, my brother,  on hand and he helped me with this.  I want to say my pr fixes this, but it's kind of hard to tell sometimes.

**Comment by Cheeseness** [comment]
I think we need a bit more clarity on what behaviour is being seen here and how to reproduce it.

Is this the "music sometimes finishes early" thing that we saw previously?

If so, does this issue suggest that that bug only manifests itself when a track has been skipped (that could explain why we were having trouble confirming whether or not it was resolved)?

**Comment by fragmental** [comment]
Yes and yes, and hopefully the pr fixes it.

**Comment by Cheeseness** [comment]
Resolved by #152! Does your brother need crediting?

**Comment by Cheeseness** [comment]
I did a whole bunch of testing for #152 and I feel that it definitely prevents the skipping that we'd previously seen.

During long play sessions though, I've had music stop after a track has ended (or at least have a pause long enough for me to assume it's stopped?). Hitting the skip button will move to the next track.

I think the current situation is probably better than the previous one, so I'll leave #152 merged. I'll reopen this issue though as it would be nice to get to the bottom of it all.

**Comment by fragmental** [comment]
@Cheeseness I asked my brother if he wanted credit and he said no thank
you.  I am going to try to convince him to get a github account though.

**Comment by fragmental** [comment]
This one may be pretty hard to track down, because I don't think it happens consistently.  I might play for 3 or 4 long sessions and have it only occur one of those times, and I think the music will also sometimes start back on its own after it has stopped.

**Comment by Cheeseness** [comment]
I'd be interested to know if isPlaying is true or false when this happens (if anybody's keen to dig in and get some more detail on the issue).

**Comment by fragmental** [comment]
well, the musicIsPlaying bool is always true, because nothing ever sets it to false.

I am interested to know if musicSource.isPlaying is true or false, as well.  I'll probably add Debug.Log for it that can get called on a button press so the next time I see the music stop, I can press the button and it will tell me.
