### ISSUE TITLE
Win prompt appears before player scores are updated.

### ISSUE THREAD

**Issue by Cheeseness** [Double-Fine-Game-Club/pongball#158]
The fall ball's value isn't added to the winning player's score before the win prompt is displayed, making it harder to read final scores.

![win_scores](https://cloud.githubusercontent.com/assets/1570520/25556262/e1ea499c-2d3c-11e7-970a-9772a1ac1821.png)
#

**Comment by osse101** [comment]
I'm not seeing this.  Is it still a problem?

**Comment by Cheeseness** [comment]
I fixed it in the score_fixes branch. Are you definitely not seeing it in the master?

**Comment by osse101** [comment]
My mistake then, it is on master

**Comment by Cheeseness** [comment]
Resolved by #168
