### ISSUE TITLE
Remove Load Assets and Basic Menu Script from Network Manager Game Object

### ISSUE THREAD

**Issue by fragmental** [Double-Fine-Game-Club/pongball#181]
Remove Load Assets and Basic Menu Script from Network Manager Game Object.
These were left over from making the new menu.

@jctwood is there any reason we should continue to leave these two scripts on the Network Manager object or is it fine to remove them?

**Comment by Cheeseness** [comment]
I think BasicMenu.cs is dead code now? Makes sense to remove it from the project entirely if it's not being used.

**Comment by fragmental** [comment]
Probably.  We left BasicMenu there as a backup in case we couldn't get the new gui up and running before the end of AF, but it's superfluous now.

Still, I'd be more comfortable waiting on word from @jctwood before removing it entirely from the project.

**Comment by Cheeseness** [comment]
It makes sense to remove unused stuff as part of PRs. We can always grab it from the repo history if we need to check stuff or revert changes.

No rush on this one. It's not a critical issue - just something to do to avoid confusion in the future.

**Comment by jctwizard** [comment]
Just woke up those are dead as Fragmental said they were there in the case
of a backup.
