### ISSUE TITLE
Ball movement erratic and gets stuck

### ISSUE THREAD

**Issue by fragmental** [Double-Fine-Game-Club/pongball#19]
Ball movement can be erratic.  Ball gets stuck, or bounces forever in the same location.  Resetting the Ball Position doesn't always function as one might expect(instead of moving along the floor it bounces around).

I'm not sure the best way to solve this, but I wanted to verbalize the issue so we can address it.

**Comment by ghost** [comment]
- On resets it will bounce in the z direction in the same spot
- Shoot off in the wrong direction on collision

These can probably be solved by better level design:
- Bouncing back and forth along the Y between walls
- Gets stuck under the ramp

**Comment by jctwizard** [comment]
Pinball maybe solves the getting stuck amid bumpers by spacing them out and having them in diagonal or triangular formations also making the bumpers themselves fairly large.

**Comment by Cheeseness** [comment]
Is this resolved by #18 ?

**Comment by fragmental** [comment]
@Cheeseness This is what remains after what #18 fixes.
Edit:  #18 keeps the ball from clipping through colliders when it's moving quickly.

**Comment by Cheeseness** [comment]
Ah, gotcha! For some reason I missed the timestamp and thought this was from yesterday >_<

**Comment by ghost** [comment]
https://drive.google.com/open?id=0B4DlVPd_1DaUZU85RXp3ZkZvR2s
https://drive.google.com/open?id=0B4DlVPd_1DaUalBobUVyQm1xbEE

**Comment by fragmental** [comment]
So I moved some bumpers under the ramp in table2 just so the ball wouldn't get stuck.... just thought I would mention that.

**Comment by Cheeseness** [comment]
#68 is relevant here.

**Comment by Cheeseness** [comment]
Closed by #68
