### ISSUE TITLE
UX/UI improvements

### ISSUE THREAD

**Issue by ehne** [Double-Fine-Game-Club/pongball#22]
## The UI desperately needs a fix.
So a will make most of the menus and buttons/text fields look nicer
- [x] main menu
- [ ] connection dialogue

suggestions welcome!

-darcy

**Comment by jctwood** [comment]
I think @fragmental may also be doing work on some UI, they posted an image at some point in the irc of the main menu looking nicer.

**Comment by Cheeseness** [comment]
I'm going to call the remainder of this issue superseded by #79
