### ISSUE TITLE
High CPU usage in build

### ISSUE THREAD

**Issue by fragmental** [Double-Fine-Game-Club/pongball#25]
I don't know if this is just a quirk of my machine or if it's something else.

Let me know if you see it too.

It's not low in the editor either, but it's something like a quarter of the build usage.

**Comment by Cheeseness** [comment]
Given the state of things currently, I'm going to push this into the post-AF milestone, where we can approach optimisation and performance analysis in a more relaxed manner :D

**Comment by fragmental** [comment]
This seems to be ok now.  I suspect it might have been related to high frame rate and ongui (not to be confused with UGUI) elements being called twice per frame(that's just the way they were designed).  So, I'm going to go ahead and close this for now.

**Comment by Cheeseness** [comment]
Awesome, glad to hear that's laid to rest :)
