### ISSUE TITLE
Add Credits Screen

### ISSUE THREAD

**Issue by Cheeseness** [Double-Fine-Game-Club/pongball#34]
The credits screen will need to parse and combine several plain text files (with unix style line endings!).

* Assets/resources/credits/credits-git.txt
* Assets/resources/credits/credits-assets-git.txt
* Assets/resources/credits/credits-extra.txt

The first two are generated using the following command, one in this repo and the other in the asset sources repo (with the output filename changed):
`git log --all --pretty=format:'%an' | sort | uniq > credits-git.txt`

The third file is for additional contributor names/details. Sometimes an asset contributor may not have a GitHub account or someone reworking a botched pull request might forget to include the original author as one of the commit's authors. Some contributors may want to include additional usernames (such as IRC, forum or Twitter handles. In this case, the GitHub author name should appear at the beginning of the line and any additional information after a space. Like so:
`Cheeseness @ValiantCheese`

The credits scene will need to parse, combine and then remove duplicates from credits-git.txt and credits-assets-git.txt. It will then need to replace values for any contributor who is included in credits-extra.txt (compare everything before the first space with what's in the combined list) with the corresponding line from credits-extra.txt and append any contributors from credits-extra.txt who are not in the combined list.

If any of that's not clear, ask questions!

@ehne sounded keen to work on this one.

**Comment by Cheeseness** [comment]
93acadeb571aa4149b8a432c6f5ae5bded710d84 Adds initial versions for the three required files.

**Comment by Cheeseness** [comment]
@ehne I've written code to handle parsing and combining the credits files, which I can add to your stuff when you're ready to commit your GUI work.

**Comment by Cheeseness** [comment]
@ehne This issue has become higher priority over the past few days and I think we need to get this in ASAP I'll take over on this one and implement it in the morning. Thanks heaps for your efforts!

**Comment by fragmental** [comment]
@Cheeseness Do you have experience working with setting the text of a text ugui object or with ugui scrollrect?

**Comment by Cheeseness** [comment]
Resolved by #84 

Don't need no scrollrects :D
