### ISSUE TITLE
Reset ball button no longer works

### ISSUE THREAD

**Issue by Cheeseness** [Double-Fine-Game-Club/pongball#36]
Seems like a recent update broke the reset ball button. Haven't had time to look into it - most likely changes brought in with single player mode?

**Comment by jctwizard** [comment]
Hmm I will have a look at this!

**Comment by Cheeseness** [comment]
With @VideogameScrapbook's automatic ball reset changes, I feel like the remaining stuff here isn't so important. @jctwood, are you happy with this issue being closed for now?

**Comment by jctwizard** [comment]
I'm happy with that now that the main game loop is in!

**Comment by Cheeseness** [comment]
In that case, closed with https://github.com/Double-Fine-Game-Club/pongball/commit/98fb3711d4671e049bb5f6af26ffda130b517a96 :D
