### ISSUE TITLE
Add single player mode

### ISSUE THREAD

**Issue by ghost** [Double-Fine-Game-Club/pongball#4]
Besides hosting and having a second client it should be possible to host a single player game.

It would spawn your character and an AI controlled character.

**Comment by Cheeseness** [comment]
@bobsayshilol has been continuing to work towards resolving this one bobsayshilol/pongball@f85c6f7f8b7519335e856b6d2c444fc86ab2e49d

**Comment by jctwizard** [comment]
as @bobsayshilol is no longer able to complete this issue I will try and take it on as I've been looking for something to dive into and would like the challenge! I have taken a look at what was being done on the forked repo and starting to wrap my head around it.

**Comment by Cheeseness** [comment]
With the merging of #31, I think we can call this one closed for now and open. Future issues can be opened to refine/build upon what we have here.
