### ISSUE TITLE
Add a basic first version of scoring system

### ISSUE THREAD

**Issue by VideogameScrapbook** [Double-Fine-Game-Club/pongball#43]
It would be good to add some sort of scoring system soon so that this moves from a "playable concept" to a "playable game".

I know there's some discussion on making the score be influenced by pinball elements, but for a first pass it could just involve basic score counters on each side, incrementing the score by 1 when the ball passes a certain collider on each side, and respawning the ball.

I've created a branch of my own for possibly adding basic scoring. I'm not the most experienced programmer, so I could hold off on doing this though if somebody else wants to tackle it first.

**Comment by jctwizard** [comment]
The trick will be syncing the score with all players across the network. If you want to tackle the scoring probably worth taking a look at this: https://docs.unity3d.com/Manual/UNetStateSync.html and ensure the score is only updated server side when the network is active.

**Comment by jctwizard** [comment]
I'm happy to look at integrating the scoring with the networking system. :)

**Comment by VideogameScrapbook** [comment]
As I said elsewhere, I got a system in place for the local scoring which can be modified to be networking friendly. @lightsoda, feel free to reassign to @jctwood since I'm not sure if and when I'll be able to contribute next.

**Comment by ghost** [comment]
Unassigned, anyone who's up for it feel free to work on this.

**Comment by Cheeseness** [comment]
Done \o/
