### ISSUE TITLE
Variant Issues

### ISSUE THREAD

**Issue by fragmental** [Double-Fine-Game-Club/pongball#47]
So, I talked to @lightsoda and he set me right on how to check variants in the editor.  I had been leaving asset bundles on simulation mode.   I didn't know you had to build the assets and then turn off simulation mode.  So I did that.  And discovered something interesting.

https://www.evernote.com/l/ATqIt9F33p1IVYxKKtkvYyFRBVZ8gFp2VdgB/image.png
:D

This is Upstream Master. variant kgunn table1.

**Comment by ghost** [comment]
Yeah, that's the ramp. I've started to realize that having them as variants is probably a bad idea, since they are basically made to fit a specific table anyway.

**Comment by fragmental** [comment]
Probably true.

Also, there seems to be some weirdness with kgunn variant on table 2 as well.  The ball sometimes, but not always, falls off the map.  I suspect it is a related issue.

**Comment by ghost** [comment]
Ok, his variant on his table? It has seemed pretty stable for me lately.

Also, off the top of my head things that can possibly break a variant:

1. Wrong name on file
2. Wrong name on mesh
3. Wrong name on material

**Comment by fragmental** [comment]
This is upstream master, still.

**Comment by Cheeseness** [comment]
Yes. This needs fixing.

The ball seems to fall outside of the map whenever hitting one of the objects that the flippers are attached to (on table 2)

**Comment by fragmental** [comment]
Also, lightsoda variant table 2, the ball sometimes falls off the map when it's being reset after scoring.   I don't know if this is related to variants or scoring, or possibly some bad geometry somewhere?  I don't know.   So far I haven't seen it fall off the map with lightsoda variant table 1, though. 
Edit:  Ok, this one is caused by the ball spawning too low.
Edit2:  Or the floor being a little too high.  It's a box, instead of a plane, so the bottom of the box is where the top of the box needs to be.  The only reason it's sort of been working so far is that there was a bumper there that the ball would bounce off, and sometimes it bounces higher and sometimes it bounces lower.  Either way, it's not a variant issue.

**Comment by fragmental** [comment]
All the issues with table 2 weren't related to variants, they were related to the ball spawner being too low or the floor being too high :/

Now the only problem is with the ramp/tube in table1 kgunn variant.

**Comment by Cheeseness** [comment]
Alrighty, going to close this, as #45 removed the ramp from table 1 and everything else seems to have been sorted?
