### ISSUE TITLE
Update kyle3wynn SFX from assets repo. 

### ISSUE THREAD

**Issue by kyle3wynn** [Double-Fine-Game-Club/pongball#51]
The new SFX have a 1 at the end because just overriding the existing files wasn't working.

**Comment by fragmental** [comment]
So, the files need to be updated from the assets repo so they can be quickly overwritten in the future?

**Comment by Cheeseness** [comment]
The updated files in the asset repo need to replace the ones in the game (ignore the stuff about files with 1 - I removed those as they were duplicates)

**Comment by fragmental** [comment]
I seem to recall something about replacing files...like, you can do it in your file manager(explorer, finder, etc) but if you do it unity it will automatically add a number.  I might have those reversed.  Anyway, it's something to watch out for.
