### ISSUE TITLE
Add networking to powers

### ISSUE THREAD

**Issue by Cheeseness** [Double-Fine-Game-Club/pongball#57]
#56 bought in player powers/abilities thanks to @osse101, but they're not currently synced across the network.

**Comment by Cheeseness** [comment]
@jctwood You did a good job on quickly syncing scores - are you up for this one too?

**Comment by jctwizard** [comment]
@Cheeseness sounds great! I'll take a look later today.

**Comment by jctwizard** [comment]
Should hopefully be closed by #62 Sorry it took so long for me to get round to implementing this, Currently I am a little unsure if it working over the network is just a result of background input and all paddles receiving the same input but I tested it thoroughly and I'm very sure it is working...

**Comment by jctwizard** [comment]
Was this closed by #69?

**Comment by Cheeseness** [comment]
Yes! Thanks for spotting that :)
