### ISSUE TITLE
Add possibility to have variants for paddles

### ISSUE THREAD

**Issue by ghost** [Double-Fine-Game-Club/pongball#6]
Paddles are spawned from the network manager and thus seem to ignore the AssetBundle variants.

We need to figure out a way to make it work to have them load from AssetBundles.

**Comment by Cheeseness** [comment]
This is now doubly relevant as we have multiple paddle contributions beyond the default "block" (maybe we want to keep that as an option?) https://github.com/Double-Fine-Game-Club/pongball-assets/pull/9

**Comment by Cheeseness** [comment]
Thanks to @lightsoda, #59 addresses the back end side of this, but we still need UI

**Comment by Cheeseness** [comment]
#79 should resolve the UI side of things. I'm going to that supersede this one and close things here..
