### ISSUE TITLE
Synchronise table selection

### ISSUE THREAD

**Issue by jctwizard** [Double-Fine-Game-Club/pongball#61]
Currently clients can connect to the server and have a different table this should be corrected so that only the server can select the table and when clients connect it loads the correct one.

**Comment by fragmental** [comment]
Did your commit solve this?

**Comment by jctwizard** [comment]
Yes as far as I know but @Cheeseness was able to test it better on his local network.

**Comment by ghost** [comment]
This is what we did during our testing right, @fragmental, I selected the table as host. Seemed to work fine.

**Comment by fragmental** [comment]
Yep, yep

**Comment by fragmental** [comment]
There were a few minor issues with someone trying to connect when there was no host, or the host disconnected before the client.  

But those are separate issues, so I think you can probably close this, if it pleases you to do so.

**Comment by jctwood** [comment]
Okay great! I don't think I can close issues though?

**Comment by jctwizard** [comment]
Okay sure!

**Comment by fragmental** [comment]
oh yeah, gj on that @jctwood
