### ISSUE TITLE
Network Table Obstacles

### ISSUE THREAD

**Issue by jctwizard** [Double-Fine-Game-Club/pongball#65]
Certain table obstacles should be synced over the network.

**Comment by jctwizard** [comment]
@fragmental mentioned that flippers should be synced.

**Comment by jctwizard** [comment]
@Cheeseness mentioned that gates should be synced.

**Comment by fragmental** [comment]
apparently gates work.  And I think the spinner does too.

I don't think flippers do, but I honestly forgot to test them.

**Comment by jctwizard** [comment]
So I'm looking at creating a system for easily (in a few lines) networking obstacles with an activate/deactivate method which would be replicated across clients. 

Unfortunately when I build, the flippers are not spawned in Table02 for the build. Running in the editor is fine. I am making sure to build asset bundles too. Anyone had this issue before?

**Comment by fragmental** [comment]
I don't recall having that issue.

**Comment by jctwizard** [comment]
Would be great if someone could check. I really cannot work out what is preventing the paddle from appearing in the build!

**Comment by fragmental** [comment]
alright, apparently everything in the variants folders need a partner in the other variant folder.  Anything without a partner won't show up if you choose the variant without it.  So if we don't have a different one we can just copy the one that's already there.

**Comment by jctwizard** [comment]
See #80 for information on networking obstacles. Currently only allows activate/deactivate functionality but can be expanded for other needs. Activate and deactivate are just descriptive and functionality is left to implementation as seen in FlipperController.
