### ISSUE TITLE
Sound Effect not playing for ball colliding with wall on Speedster map.

### ISSUE THREAD

**Issue by kyle3wynn** [Double-Fine-Game-Club/pongball#67]
At least on Speedster, there is no SFX playing when the ball collides with a wall.

**Comment by fragmental** [comment]
The table needs a "Wall" tag on all of the wall objects.  There may be other maps that need this as well.  Table 2 is the one I had open when working on this.

**Comment by Cheeseness** [comment]
Fixed in #102
