### ISSUE TITLE
Configurable AssetBundle variants

### ISSUE THREAD

**Issue by ghost** [Double-Fine-Game-Club/pongball#7]
Currently the two variants (normal, alternate) are hardcoded, it should be possible to configure this more dynamically.

Unless it's prefereable to keep it hardcoded.

**Comment by Cheeseness** [comment]
@lightsoda Have you worked on this as part of the variant stuff you've been working on over the past couple of days?

**Comment by Cheeseness** [comment]
After further discussion, it seems that asset variants are as configurable as tables are (a matter of dropping things in the right place and adding their name to a list of available variants). That's configurable enough for me!
