### ISSUE TITLE
Online Multiplayer Issue with Ball

### ISSUE THREAD

**Issue by fragmental** [Double-Fine-Game-Club/pongball#71]
I did some online multiplayer play testing with @lightsoda 

I was client side.  He was host.  I didn't realize until later that there's a very good chance that the video I was uploading caused severe latency:/  Need to retest when that's not a factor.

The biggest issue was the ball fighting with my paddle.  It would sort of bounce away and then bounce back and do that repeatedly.  According to lightsoda it looked like I was just missing.

There were some issues with the ball not following the exact same path as well.  It was close, but it would sort of stop short of the wall, cut a corner a little closer, etc.
 
We tried upping network send rate to 29 for both the ball and the paddles and that may have helped with some issues.

We were also seeing a lot of activity in the debug.log.  It was very cluttered.  A lot of it was messages from one of the paddles looking for an animator.  "parameter hit"

There were a few errors:
This would display once.
Spawn scene object not found for 1
UnityEngine.Networking.NetworkIdentity:UNetStaticUpdate()

One was this if host disconnected before client
ClientDisconnected due to error: Timeout
UnityEngine.Networking.NetworkIdentity:UNetStaticUpdate()

I think this would display every time the ball hit a paddle.
NullReferenceException: Object reference not set to an instance of an object
Ball.OnCollisionExit (UnityEngine.Collision other) (at Assets/scripts/entity/Ball.cs:112)
(lightsoda told me what would fix this, but we didn't have time to test it)

i would have made a branch and made a pr, but the changes were minor and I made them on the wrong local clone.

**Comment by ghost** [comment]
A potential cause for the ball "fighting" the paddle could be the places where we apply force, I don't think that's only server-side atm.

**Comment by jctwizard** [comment]
Yeah I think we should disable the collision on the client's paddles perhaps?

**Comment by fragmental** [comment]
#74 addresses the 
NullReferenceException: Object reference not set to an instance of an object
Ball.OnCollisionExit (UnityEngine.Collision other) (at Assets/scripts/entity/Ball.cs:112)

and disable client side collision with paddle

and a reset ball issue I forgot about.

Edit: But didn't get a chance to test the former.

**Comment by fragmental** [comment]
So here's an interesting thing.  Network Send Rate actually changes a m_SendIntervalValue in the prefab.

https://docs.unity3d.com/ScriptReference/Networking.NetworkSettingsAttribute-sendInterval.html

Changing it from 9 to 29 changed it from 0.11111111 to 0.033333335

I didn't get this changes in my PR, because unity was being weird about updating my prefabs or something, so they didn't show up as files I could stage.

**Comment by fragmental** [comment]
https://drive.google.com/file/d/0B4DlVPd_1DaURzZ2NHA5RXNGR28/view this is host side

**Comment by Cheeseness** [comment]
Adding this to the post-AF milestone for now unless someone wants to look at it in the meantime (@jctwood?)

**Comment by Cheeseness** [comment]
OK, so far as I can tell, this can be closed now. There have been a bunch of ball changes and the last video in this thread shows a physics collision between paddles and bumpers that's no longer relevant. If there are more issues that haven't been resolved, let's open a new thread
