### ISSUE TITLE
Refine Paddle Controls

### ISSUE THREAD

**Issue by Cheeseness** [Double-Fine-Game-Club/pongball#77]
Paddle controls need some refinement. @fragmental is keen to work on this.

The following options have been discussed (there's unlikely to be value in combining them, so consider them separate things to weigh up the value of):

* Rotational controls
* Curved colliders
* 2D paddle movement (with paddle vector at impact influencing ball deflection vector)

Additionally, "serve" mechanics needs to be implemented, and a "grab and throw" mechanic is being considered.

Further discussion is [here](https://forums.doublefine.com/topic/17250-paddle-controls-gameplay/)

**Comment by ghost** [comment]
Taking a look at curved colliders.

Or wait, were we going to check rotation first? I'll hold off on this.

**Comment by Cheeseness** [comment]
I think we're pushing off messing with rotation for now. Curved colliders feels like a safer short term area to investigate with low risk of lost time.
