### ISSUE TITLE
Support Multiple Input Devices

### ISSUE THREAD

**Issue by Cheeseness** [Double-Fine-Game-Club/pongball#78]
For local multiplayer to be functional, the game needs to handle multiple input devices.

Discussion during today's contributor catchup identified that it would be desirable to address or at least design any implementation with consideration for user configurable key/button bindings.

**Comment by fragmental** [comment]
I may do this first today, just because.  Sometimes the hardest thing for me is deciding what to do first.

Edit: by just because I mean, because playtesting

**Comment by fragmental** [comment]
This is turning out to be complex than I had anticipated.

Ok it seems like first we need to set up all the inputs for both devices.
http://answers.unity3d.com/questions/333923/joysticks-and-the-input-manager-joystick-1-recogni.html


The defaults should be for xbox360 controllers. 
Reference for that can be found here.
http://wiki.unity3d.com/index.php?title=Xbox360Controller
Looks like they may have to be assigned from a script to support mac/win/linux?  But I'm not sure.
Any other device may have the wrong inputs but that's probably just something we'll have to accept for now.

Reference for the rest of the buttons can be found here.
Here is a list of keys https://docs.unity3d.com/ScriptReference/KeyCode.html

Then our script on the prefabs need to know which player they're on, either player 1 or 2, and set the player num variable.
http://answers.unity3d.com/questions/872646/setting-up-two-players-local-multiplayer.html


That's the basics, I think.  If we can edit the inputmanager.asset file by hand, that might be quicker. Or maybe there's some kind of script wizardry that would make it easier?

I can't help but think that a ready made solution would be a lot faster to get working, but most of them will probably be license and redistribution incompatible.    There's https://github.com/speps/XInputDotNet but that's for windows only.

**Comment by fragmental** [comment]
https://github.com/fragmental/ControllerManager this could potentially useful

**Comment by fragmental** [comment]
#86 addresses, but does not entirely solve this issue.  

In the time I had I was unable to satisfactorily solve the problem of supporting multiple devices or multiple operating systems with one device.

here is a spreadsheet of all the mappings
https://docs.google.com/spreadsheets/d/1kVCnyqB_bOmdG4OHTMRGA_RJbEJmf2IQxUTzeJce8hw/edit?usp=sharing

other buttons probably unmapped but should be mapped
start button
back button
select

UI navigation

**Comment by Cheeseness** [comment]
Let's call this resolved with #91 

Input bindings have been modified by @osse01 a little. They need to be tuned, but are:

(10:09:10) Osse: Current controls are: p1) up down space left-alt p2) y h q z
(10:12:45) Osse: p1) right-ctrl right-ctrl p2) left-alt left-ctrl
(10:12:48) Osse: for flippers

I'm going to close this for now. We can reopen an issue for changing the bindings if we need.

**Comment by fragmental** [comment]
I want to reopen this, because the way unity handles joysticks is garbage, and this issue has the most important information in it.  Feel free to link other issues to this, or rename this , if possible

Buttons are different across multiple devices. And they're different on the same device on each platform.

To reiterate, we should map to xbox360 bindings on win32, until we can find a better solution, because that is the most widely used platform.

If you don't have that device/platform combination testing and playing the game is more difficult, which is why I had them mapped to my controller on osx.

Edit: another reason to target x360 is that I think it should map the same on all xinput devices.

https://github.com/fragmental/ControllerManager might then allows us to accurately map to all xinput devices on all platforms.  That would still leave users with dinput controllers to have to use something like x360 ce or just hand remap to their joystick, but that's at least on par with a lot of the games that are out today.

Edit 2:  The only reason I didn't try to use ControllerManager is that I couldn't figure out how to get it to work at the time and wanted to get something that was working and then revisit it.

**Comment by Cheeseness** [comment]
So far as I can tell they're consistent across all platforms (it's Windows users reporting that the powers and flippers aren't bound). Remember that you're way out of sync with upstream. It might be best to hold off on opening/reopening issues till you're all caught up.

I'd rather have fresh issues to address specific concerns thank link to this issue, but I'll leave it open for now until it looks like stuff is fine.

**Comment by fragmental** [comment]
" but I'll leave it open for now "

it's closed.

"So far as I can tell they're consistent across all platforms. "
Time and testing will tell.  Seems like everyone and their mother wants to remap them, though.  The information is here for anyone who wants it.  ~~I have nothing else to add.~~

**Comment by fragmental** [comment]
Well, I say that, but here is the relevant information on the bumper buttons

https://github.com/Double-Fine-Game-Club/pongball/blob/8d2cb5448314001c2cc6104c521cbfa57d966e5a/ProjectSettings/InputManager.asset
No one has remapped the flipper controls so they're still set to R1 and L1 on my controller, which is Button6 for R1 and Button7 for L1

For xbox360 the same buttons on windows and linux  should be Button4 for R1  and Button5 L1 , and x360 on osx Button13 for R1 and Button14 for L1

**Comment by Cheeseness** [comment]
>it's closed.

I thought you'd opened it, sorry.

> Time and testing will tell

Time and testing *have* told. Testing feedback is why people are asking for stuff to be changed. Testing feedback is why I'm working on it.

Windows users with Xbox 360 gamepads have reported that the bindings aren't right. What's in the game now doesn't match what's on the [Unity wiki](http://wiki.unity3d.com/index.php?title=Xbox360Controller), so I'm fixing that up.

Keyboard users are reporting the having the right player try to reach space and left alt is awkward when the left player is using Y and H.

**Comment by fragmental** [comment]
so, provided at http://wiki.unity3d.com/index.php?title=Xbox360Controller is correct, most, but not all of the relevant buttons on windows and linux will be the same.  it's just osx that has super weird button locations.

And other dinput controllers, like mine will still have to be remapped by the player.

I would be over the moon to see proof that unity has in fact made mapping more consistent across platforms and devices.  At least x360 between mac, linux, and windows.

**Comment by Cheeseness** [comment]
The wiki page is from 2015. It's definitely out of date for Linux button mappings, but the windows numbers for everything relevant are the match my gamepad on Linux, and based on @lightsoda's pull request and feedback from rheberling in chat, they're matching real xbox 360 gamepad button ordering on Windows.

Let's leave it be for now and grab some feedback from you after you've had a chance to try the changes I'm working on now.

**Comment by fragmental** [comment]
Change the 6 to a 4 and the 7 to a 5 and the flippers should work with r1 and l1 on your 360 device.

**Comment by Cheeseness** [comment]
I can work on this on my own, thanks

**Comment by fragmental** [comment]
My apologies

On Apr 27, 2017 12:32 AM, "Cheeseness" <notifications@github.com> wrote:

I can work on this on my own, thanks

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Double-Fine-Game-Club/pongball/issues/78#issuecomment-297609079>,
or mute the thread

**Comment by Cheeseness** [comment]
Apologies if I've been short here.

I've popped up some changes in #129 that address legitimate bugs that came in with the first implementation (where exactly they originated, I don't know and don't really feel much value in hunting down - the only thing that matters is that they've been fixed), and tries to address the feedback we've gotten today regarding layout awkwardness.
