### ISSUE TITLE
Fix basic player movement

### ISSUE THREAD

**Issue by ghost** [Double-Fine-Game-Club/pongball#8]
Currently the characters move up and down, not restricted in any way.

**Comment by Cheeseness** [comment]
Paddle movement is currently restricted to something close to the bounds of most tables. With some, there's enough room for the ball to slip past the paddle though, so that'd be nice to look at/address if possible.

**Comment by ghost** [comment]
It's just a float value that can be increased here: https://github.com/Double-Fine-Game-Club/pongball/blob/master/Assets/scripts/entity/PaddleBase.cs#L70

**Comment by Cheeseness** [comment]
Oh whoops. I'd already done this and had forgotten to close the issue.

Fixed by #100
