### ISSUE TITLE
Add a main menu

### ISSUE THREAD

**Issue by ghost** [Double-Fine-Game-Club/pongball#9]
Could be a fixup of the current menu showing up with the network interface et.c. But we could also add a separate main menu ahead of this. Either way, we'd need a main menu with options like Play Game, Options, Quit...

Keep in mind that the assets used for the menu should be in AssetBundles to allow for variants.

**Comment by fragmental** [comment]
I have some experience using UGui.  I noticed the menu so far is using OnGui, which is nice from a programmer's perspective, but can use a lot of cpu cycles.  Should I go ahead and start working on the menu now or should that wait for later?  I could go ahead and create a mockup scene using ugui and then we could modify as needed?  

I don't know how uGUI will factor into using AssetBundle assets however.

**Comment by Cheeseness** [comment]
We were previously discussing  and looking toward an implementation that had menu behaviour scripts dynamically applied when menu scenes were loaded based on the name of the GameObject that represents each menu item. The hope then being that menu behaviour would be entirely separated from menu presentation, and multiple contributions for a given menu would be easier to implement/work with.

**Comment by fragmental** [comment]
@Cheeseness I honestly have no idea how to do that, but it sounds cool.  In the meantime, I made a placeholder.  #20  I really won't be hurt in the slightest if it gets scrapped later, but I can also improve upon it if need be.

**Comment by Cheeseness** [comment]
With #20 merged now, I might close this. People can iterate on or improve on what's there, but for now, this is good :)
